apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: web2
  name: web2
  namespace: dev
spec:
  containers:
  - image: nginx
    name: web2-container
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
